# Generated by Django 2.2.1 on 2019-05-16 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190516_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(help_text='address of the clinic', max_length=300, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 16, 19, 16, 3, 688322, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='reserver',
            field=models.ForeignKey(blank=True, default=None, help_text='reserver of the this timeslot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.BasicUser', verbose_name='reserver'),
        ),
    ]
