# Generated by Django 2.2.1 on 2019-05-16 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20190516_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='clinic',
            field=models.ForeignKey(help_text='the clinic that this time slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='clinic.Clinic', verbose_name='clinic'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 16, 20, 12, 35, 414665, tzinfo=utc), verbose_name='end time'),
        ),
    ]
