# Generated by Django 2.2.1 on 2019-05-16 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20190516_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='rep',
            field=models.ForeignKey(help_text='representative of the clinic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinic.ClinicRepresentative', verbose_name='rep'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 0, 23, 27, 462692, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='reserver',
            field=models.ForeignKey(blank=True, default=None, help_text='reserver of the this timeslot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slots', to='clinic.BasicUser', verbose_name='reserver'),
        ),
    ]
