# Generated by Django 2.2.1 on 2019-05-16 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20190516_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='test_clinic_1', help_text='name of the clinic', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 1, 3, 43, 12120, tzinfo=utc), verbose_name='end time'),
        ),
    ]
