# Generated by Django 2.2.1 on 2019-05-17 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20190516_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicrepresentative',
            name='user',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='rep',
            field=models.ForeignKey(help_text='representative of the clinic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to=settings.AUTH_USER_MODEL, verbose_name='rep'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 17, 27, 16, 998561, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='reserver',
            field=models.ForeignKey(blank=True, default=None, help_text='reserver of the this timeslot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slots', to=settings.AUTH_USER_MODEL, verbose_name='reserver'),
        ),
        migrations.DeleteModel(
            name='BasicUser',
        ),
        migrations.DeleteModel(
            name='ClinicRepresentative',
        ),
    ]
