# Generated by Django 2.2.1 on 2019-05-18 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20190517_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified by admin'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 18, 7, 56, 10, 924364, tzinfo=utc), verbose_name='end time'),
        ),
    ]
