# Generated by Django 2.2.1 on 2019-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20190518_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='start time'),
        ),
    ]
